In [1]:
#Problem 1
#1
#creates a 2x2 Numpy array which is uninitialized
import numpy as np
emptyArr = np.empty((2,2))
print(emptyArr)


[[3.22610946e-315 0.00000000e+000]
 [6.58696018e-310 6.58696040e-310]]


In [2]:
#2
#creates a 4x2 Numpy array made up of 1s.
import numpy as np
Arr = np.ones((4,2))
print(Arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#3
#creates a 2x2 Numpy array which value is inputed,i.e 1 here.
import numpy as np
fullArr = np.full((2,2),1)
print(fullArr)

[[1 1]
 [1 1]]


In [5]:
#4
#creates a new array of zeroes which has same shape as a.
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
zerosLiker = np.zeros_like(a)
print(zerosLiker)

[[0 0 0]
 [0 0 0]]


In [6]:
#5
#creates an array like a made of 1s.
import numpy as np
a=np.array([[2,2],[3,3]])
oneLiker = np.ones_like(a)
print(oneLiker)

[[1 1]
 [1 1]]


In [7]:
#6
#converts a python list to numpy array.
import numpy as np
new_list = [1,2,3,4]
arrayTime = np.array(new_list)
print(arrayTime)

[1 2 3 4]


In [8]:
#Problem 2
#1
#Creates a numpy array from 10 to 50-1.
import numpy as np
arr=np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#2
#creates a 3x3 numpy array from 0 to 8.
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#3
#creates an identity matrix.
import numpy as np
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#4
#finds the mean of 30 randomly generated numbers.
randomStuff = np.random.random(30)
average = randomStuff.mean()
print(randomStuff)
print(f"Mean:{average}")

[0.82222037 0.77197249 0.24391629 0.29833087 0.16416873 0.59700659
 0.33120452 0.13468945 0.91908986 0.42495155 0.33897769 0.51277721
 0.40472764 0.23064213 0.11770974 0.65802727 0.20120258 0.61815114
 0.14870056 0.72426367 0.20089611 0.75749353 0.51645788 0.01795139
 0.99791208 0.55293752 0.61923729 0.32534781 0.82402256 0.7741878 ]
Mean:0.4749724776954409


In [12]:
#5
#generates 10x10 array of random numbers and prints its min and max.
randomly = np.random.random((10,10))
mini= randomly.min()
notMini = randomly.max()
print(randomly)
print(f"min: {mini}")
print(f"max: {notMini}")

[[0.97268726 0.82935184 0.54365726 0.53916816 0.41413417 0.54314016
  0.91071675 0.80327346 0.81648885 0.22230408]
 [0.88346362 0.20063213 0.22788777 0.1993642  0.57823032 0.85450086
  0.12008388 0.76384462 0.76392808 0.41096712]
 [0.38320691 0.44165924 0.12048443 0.23511494 0.85101831 0.13117819
  0.71164168 0.67631868 0.63921277 0.93049043]
 [0.22809266 0.81845646 0.30229971 0.53505397 0.3785437  0.88666413
  0.98571481 0.22573374 0.68067782 0.27218739]
 [0.2059572  0.13847112 0.92015644 0.34776638 0.82247321 0.81628973
  0.87352961 0.54693892 0.78677494 0.069444  ]
 [0.10273837 0.28030062 0.60402019 0.65111023 0.39093466 0.50064302
  0.82914857 0.92057399 0.93324891 0.17536031]
 [0.67795439 0.3483004  0.49118475 0.67914978 0.82754466 0.76716244
  0.02637425 0.61204702 0.56891253 0.84015165]
 [0.81919613 0.08686281 0.80958438 0.59388312 0.58941167 0.76569481
  0.51494612 0.86061218 0.82220922 0.82594044]
 [0.69006813 0.37597905 0.61228887 0.15729898 0.13383007 0.27959281
  0.28607108

In [13]:
#6
#creates a array of 10 zeroes and replaces the 5th element with 1.
geass = np.zeros(10)
geass[4] = 1
print(geass)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7
#reverses the array.
arr = [1,2,0,0,4,0]
reverser = arr[::-1]
print(reverser)


[0, 4, 0, 0, 2, 1]


In [15]:
#8
#creates a 6x6 array and makes the inner part replaced with zeros.
arr = np.ones((6,6))
arr[1:-1,1:-1]=0 #-1 means last element
print(arr)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
#9
#creates a 8x8 checkerboard pattern.
checker = np.zeros((8,8))
checker[1::2,::2] = 1 #(1,0),(3,2),(5,4),(7,6)
checker[::2,1::2]=1 #(0,1),(2,3),(4,5),(6,7)
print(checker)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [17]:
#Problem 3
#1
#Adds 2x2 numpy arrays.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

sum = x + y
print(sum)


[[ 6  8]
 [10 13]]


In [18]:
#2
#subtracts 2x2 numpy arrays.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
sub= x-y
print(sub)

[[-4 -4]
 [-4 -3]]


In [19]:
#3
#multiplies the 2x2 numpy array by 2.
x = np.array([[1, 2], [3, 5]])
mult = x*2
print(mult)


[[ 2  4]
 [ 6 10]]


In [20]:
#4
#squares the 2x2 numpy array's elements.
x = np.array([[1, 2], [3, 5]])
square = x**2
print(square)

[[ 1  4]
 [ 9 25]]


In [21]:
#5
#Dot product between numpy arrays.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

vwDot = np.dot(v,w)
xvDot = np.dot(x,v)
xyDot = np.dot(x,y)

print(vwDot)
print(xvDot)
print(xyDot)



219
[29 77]
[[19 22]
 [50 58]]


In [22]:
#6
#Concatenates numpay arrays after rshaping either vertically or horizontally.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10]).reshape(2,1)
w = np.array([11,12]).reshape(2,1)
xy = np.concatenate((x,y),axis =0)
vw = np.concatenate((v,w),axis =1)
print(xy)
print(vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [23]:
#7
x = np.array([[1,2],[3,5]])
#v = np.array([9,10])
#because x is a 2D array whreas v is a 1D array
#to fix
v = np.array([9,10]).reshape(1,2)
contra = np.concatenate((x,v),axis =0)
print(v)
print(f"to fix: {contra}")


[[ 9 10]]
to fix: [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [24]:
#Problem 4
#1
#calculates the inverse of matrix and proves that A.A(inverse)= I
A = np.array([[3, 4], [7, 8]])

aInv = np.linalg.inv(A)
result = np.dot(A,aInv)
print("A inv is :" , aInv)
print("A * Ainv: ",result )


A inv is : [[-2.    1.  ]
 [ 1.75 -0.75]]
A * Ainv:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [25]:
#2
#multiplies matrix A and B in order AB and BA to prove AB!=BA
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [26]:
#3
#Verifies that (AB)T = BT AT , T = Transverse
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A,B)

left = AB.T

aFlip = A.T
bFlip = B.T

right  = np.dot(bFlip,aFlip)
print(left)

print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [27]:

#4
#Solves a system of linear equation Ax = B
A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B = np.array([-1, -3, 9])

solution = np.linalg.solve(A, B)

print("Solution", solution)


Solution [ 2.  1. -2.]


In [28]:
#4.2
#Comparing addition speed between python list and numpy array.
import time
import random
import numpy as np

list1 = [random.random() for _ in range(1_000_000)]
list2 = [random.random() for _ in range(1_000_000)]

#Python list addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python list addition time:", end - start, "seconds")
arr1 = np.random.rand(1_000_000)
arr2 = np.random.rand(1_000_000)

#Numpy array addition
start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start, "seconds")



Python list addition time: 0.14438509941101074 seconds
NumPy addition time: 0.008552789688110352 seconds


In [29]:
#Comparing multication speed between python list and numpy array.

#python
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

#numpy
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start, "seconds")


Python list multiplication time: 0.12884974479675293 seconds
NumPy multiplication time: 0.008241653442382812 seconds
